"""enforce consensus legacy snapshot identity

Revision ID: 00b1fb118089
Revises: 9747a3d3b279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "00b1fb118089"
down_revision: str | Sequence[str] | None = "9747a3d3b279"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_consensus_legacy_batch_snapshot",
        "consensus_estimate_batches",
        ["source_digest", "normalizer_version", "snapshot_date"],
        unique=True,
        postgresql_where=sa.text("observed_at IS NULL"),
    )
    op.create_check_constraint(
        op.f("ck_consensus_estimate_batches_source_observation_time"),
        "consensus_estimate_batches",
        "(source_kind = 'LEGACY_WORKBOOK' AND observed_at IS NULL) OR "
        "(source_kind = 'PROVIDER_RESPONSE' AND observed_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_consensus_estimate_batches_source_observation_time"),
        "consensus_estimate_batches",
        type_="check",
    )
    op.drop_index(
        "uq_consensus_legacy_batch_snapshot",
        table_name="consensus_estimate_batches",
        postgresql_where=sa.text("observed_at IS NULL"),
    )
    # ### end Alembic commands ###
