"""canonical market facts and price regime

Revision ID: 01773da3b70f
Revises: a5bfc471caef
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01773da3b70f"
down_revision: str | Sequence[str] | None = "a5bfc471caef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=28, scale=14), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_fx_observations_actor")
        ),
        sa.CheckConstraint(
            "base_currency <> quote_currency", name=op.f("ck_fx_observations_distinct_currencies")
        ),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_observations_positive_rate")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_observations")),
    )
    op.create_index(
        "ix_fx_observations_pair_effective",
        "fx_observations",
        ["base_currency", "quote_currency", "effective_at"],
        unique=False,
    )
    op.create_table(
        "market_data_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("workbook_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_updated_text", sa.String(length=120), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_summary", sa.JSON(), nullable=False),
        sa.Column("reconciliation", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "length(source_digest) = 64", name=op.f("ck_market_data_batches_source_digest")
        ),
        sa.CheckConstraint(
            "length(workbook_sha256) = 64", name=op.f("ck_market_data_batches_workbook_sha256")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_batches")),
        sa.UniqueConstraint("source_digest", name=op.f("uq_market_data_batches_source_digest")),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("source_action_id", sa.String(length=120), nullable=False),
        sa.Column("effective_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action_type", sa.String(length=80), nullable=False),
        sa.Column("ratio_before", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ratio_after", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("old_symbol", sa.String(length=120), nullable=True),
        sa.Column("new_symbol", sa.String(length=120), nullable=True),
        sa.Column("old_exchange", sa.String(length=120), nullable=True),
        sa.Column("new_exchange", sa.String(length=120), nullable=True),
        sa.Column("currency_before", sa.String(length=3), nullable=True),
        sa.Column("currency_after", sa.String(length=3), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("verified IN (true, false)", name=op.f("ck_corporate_actions_verified")),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["market_data_batches.id"],
            name=op.f("fk_corporate_actions_batch_id_market_data_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_corporate_actions_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint("source_action_id", name="uq_corporate_actions_source_action_id"),
    )
    op.create_index(
        op.f("ix_corporate_actions_listing_id"), "corporate_actions", ["listing_id"], unique=False
    )
    op.create_table(
        "price_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("market_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_close", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("split_adjusted_close", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("total_return_close", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("volume", sa.Numeric(precision=28, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=120), nullable=False),
        sa.Column("provider_symbol", sa.String(length=120), nullable=False),
        sa.Column("adjustment_basis", sa.String(length=500), nullable=False),
        sa.Column("data_quality", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=500), nullable=False),
        sa.Column("supersedes_observation_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "data_quality IN ('PASS','PASS_VERIFIED_FALLBACK','UNSPECIFIED','INVALID')",
            name=op.f("ck_price_observations_data_quality"),
        ),
        sa.CheckConstraint(
            "provider_close IS NULL OR provider_close > 0",
            name=op.f("ck_price_observations_provider_close"),
        ),
        sa.CheckConstraint(
            "split_adjusted_close IS NULL OR split_adjusted_close > 0",
            name=op.f("ck_price_observations_split_adjusted_close"),
        ),
        sa.CheckConstraint(
            "total_return_close IS NULL OR total_return_close > 0",
            name=op.f("ck_price_observations_total_return_close"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["market_data_batches.id"],
            name=op.f("fk_price_observations_batch_id_market_data_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_price_observations_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_observation_id"],
            ["price_observations.id"],
            name=op.f("fk_price_observations_supersedes_observation_id_price_observations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_observations")),
        sa.UniqueConstraint("source_ref", name="uq_price_observations_source_ref"),
        sa.UniqueConstraint(
            "supersedes_observation_id",
            name=op.f("uq_price_observations_supersedes_observation_id"),
        ),
    )
    op.create_index(
        op.f("ix_price_observations_batch_id"), "price_observations", ["batch_id"], unique=False
    )
    op.create_index(
        "ix_price_observations_listing_date",
        "price_observations",
        ["listing_id", "market_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_observations_listing_id"), "price_observations", ["listing_id"], unique=False
    )
    op.create_table(
        "price_regime_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_close", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("split_adjusted_close", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("dma_20", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("dma_50", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("dma_200", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("high_52w", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("drawdown_52w", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("vs_dma_20", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("vs_dma_50", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("vs_dma_200", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("return_1m", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("return_3m", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("return_6m", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("realized_vol_20d", sa.Numeric(precision=18, scale=12), nullable=True),
        sa.Column("trend_state", sa.String(length=40), nullable=True),
        sa.Column("correction_state", sa.String(length=40), nullable=True),
        sa.Column("regime", sa.String(length=80), nullable=True),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("quality_reason", sa.String(length=1000), nullable=True),
        sa.Column("methodology_version", sa.String(length=40), nullable=False),
        sa.Column("source_ref", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "data_quality IN ('PASS','DATA_CHECK','UNSPECIFIED')",
            name=op.f("ck_price_regime_snapshots_data_quality"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["market_data_batches.id"],
            name=op.f("fk_price_regime_snapshots_batch_id_market_data_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_price_regime_snapshots_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_regime_snapshots")),
        sa.UniqueConstraint("batch_id", "listing_id", name="uq_price_regime_batch_listing"),
    )
    op.create_index(
        "ix_price_regime_listing_date",
        "price_regime_snapshots",
        ["listing_id", "as_of"],
        unique=False,
    )
    op.create_index(
        op.f("ix_price_regime_snapshots_listing_id"),
        "price_regime_snapshots",
        ["listing_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_price_regime_snapshots_listing_id"), table_name="price_regime_snapshots")
    op.drop_index("ix_price_regime_listing_date", table_name="price_regime_snapshots")
    op.drop_table("price_regime_snapshots")
    op.drop_index(op.f("ix_price_observations_listing_id"), table_name="price_observations")
    op.drop_index("ix_price_observations_listing_date", table_name="price_observations")
    op.drop_index(op.f("ix_price_observations_batch_id"), table_name="price_observations")
    op.drop_table("price_observations")
    op.drop_index(op.f("ix_corporate_actions_listing_id"), table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_table("market_data_batches")
    op.drop_index("ix_fx_observations_pair_effective", table_name="fx_observations")
    op.drop_table("fx_observations")
    # ### end Alembic commands ###
