"""Preserve exact three-decimal score observations

Revision ID: 45571a6d359b
Revises: ac6e0a489b51
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "45571a6d359b"
down_revision: str | Sequence[str] | None = "ac6e0a489b51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_assessments",
        "score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.Numeric(precision=4, scale=3),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_assessments",
        "score",
        existing_type=sa.Numeric(precision=4, scale=3),
        type_=sa.NUMERIC(precision=4, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
