"""canonical source document catalog

Revision ID: 508a1bb35c90
Revises: a9c138fdd222
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "508a1bb35c90"
down_revision: str | Sequence[str] | None = "a9c138fdd222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_document_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=120), nullable=False),
        sa.Column("provider_schema_version", sa.String(length=120), nullable=True),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("query_scope", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_summary", sa.JSON(), nullable=False),
        sa.Column("reconciliation", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "domain = 'SOURCE_DOCUMENTS'", name=op.f("ck_source_document_batches_domain")
        ),
        sa.CheckConstraint(
            "length(source_digest) = 64", name=op.f("ck_source_document_batches_source_digest")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document_batches")),
        sa.UniqueConstraint(
            "source_digest", "normalizer_version", name="uq_source_document_batches_digest_version"
        ),
    )
    op.create_table(
        "source_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("security_id", sa.Uuid(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.String(length=120), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_jurisdiction", sa.String(length=80), nullable=True),
        sa.Column("external_identifier", sa.String(length=500), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("source_form", sa.String(length=40), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("reporting_period", sa.String(length=120), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_period", sa.String(length=40), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("filed_at", sa.Date(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("canonical_url", sa.String(length=2000), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_amendment", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("amends_document_id", sa.Uuid(), nullable=True),
        sa.Column("supersedes_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "data_quality", sa.String(length=20), server_default=sa.text("'PASS'"), nullable=False
        ),
        sa.Column("quality_reason", sa.String(length=1000), nullable=True),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_source_documents_actor")
        ),
        sa.CheckConstraint(
            "data_quality IN ('PASS','DATA_CHECK')", name=op.f("ck_source_documents_data_quality")
        ),
        sa.CheckConstraint(
            "document_type IN ('10-K','10-Q','8-K','20-F','6-K','ANNUAL_REPORT',"
            "'EARNINGS_RELEASE','OTHER')",
            name=op.f("ck_source_documents_document_type"),
        ),
        sa.CheckConstraint(
            "length(canonical_url) > 0", name=op.f("ck_source_documents_canonical_url")
        ),
        sa.CheckConstraint("length(source_name) > 0", name=op.f("ck_source_documents_source_name")),
        sa.CheckConstraint(
            "batch_id IS NOT NULL OR retrieved_at IS NULL",
            name=op.f("ck_source_documents_retrieved_only_for_ingested_source"),
        ),
        sa.ForeignKeyConstraint(
            ["amends_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_amends_document_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["source_document_batches.id"],
            name=op.f("fk_source_documents_batch_id_source_document_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_source_documents_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_source_documents_security_id_securities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_supersedes_document_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint(
            "provider_id", "external_identifier", name="uq_source_document_provider_external_id"
        ),
    )
    op.create_index(
        "ix_source_documents_company_published",
        "source_documents",
        ["company_id", "published_at"],
        unique=False,
    )
    op.add_column(
        "external_raw_payloads", sa.Column("source_document_batch_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_external_raw_payloads_source_document_batch_id"),
        "external_raw_payloads",
        ["source_document_batch_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_external_payload_source_document_batch_record",
        "external_raw_payloads",
        ["source_document_batch_id", "source_record_id"],
    )
    op.create_foreign_key(
        "fk_external_raw_payloads_source_document_batch",
        "external_raw_payloads",
        "source_document_batches",
        ["source_document_batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.execute(
        """DO $$ DECLARE item record; BEGIN
        FOR item IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'external_raw_payloads'::regclass
              AND contype = 'c'
              AND (
                  lower(pg_get_constraintdef(oid)) LIKE '%reported_fundamental_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%consensus_estimate_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%source_document_batch_id%'
              )
        LOOP
            EXECUTE format('ALTER TABLE external_raw_payloads DROP CONSTRAINT %I', item.conname);
        END LOOP;
        END $$"""
    )
    op.create_check_constraint(
        op.f("ck_external_raw_payloads_exactly_one_batch"),
        "external_raw_payloads",
        "num_nonnulls(batch_id, reported_fundamental_batch_id, "
        "consensus_estimate_batch_id, source_document_batch_id) = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """DO $$ DECLARE item record; BEGIN
        FOR item IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'external_raw_payloads'::regclass
              AND contype = 'c'
              AND (
                  lower(pg_get_constraintdef(oid)) LIKE '%reported_fundamental_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%consensus_estimate_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%source_document_batch_id%'
              )
        LOOP
            EXECUTE format('ALTER TABLE external_raw_payloads DROP CONSTRAINT %I', item.conname);
        END LOOP;
        END $$"""
    )
    op.create_check_constraint(
        op.f("ck_external_raw_payloads_exactly_one_batch"),
        "external_raw_payloads",
        "num_nonnulls(batch_id, reported_fundamental_batch_id, consensus_estimate_batch_id) = 1",
    )
    op.drop_constraint(
        "fk_external_raw_payloads_source_document_batch",
        "external_raw_payloads",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_external_payload_source_document_batch_record", "external_raw_payloads", type_="unique"
    )
    op.drop_index(
        op.f("ix_external_raw_payloads_source_document_batch_id"),
        table_name="external_raw_payloads",
    )
    op.drop_column("external_raw_payloads", "source_document_batch_id")
    op.drop_index("ix_source_documents_company_published", table_name="source_documents")
    op.drop_table("source_documents")
    op.drop_table("source_document_batches")
    # ### end Alembic commands ###
