"""add execution pace snapshots

Revision ID: 8f96876cc9e9
Revises: a820d4e6f119
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8f96876cc9e9"
down_revision: str | Sequence[str] | None = "a820d4e6f119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_pace_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("methodology_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_execution_pace_runs_actor")
        ),
        sa.CheckConstraint(
            "status IN ('COMPLETE','PARTIAL','UNAVAILABLE')",
            name=op.f("ck_execution_pace_runs_status"),
        ),
        sa.CheckConstraint(
            "length(methodology_version) > 0",
            name=op.f("ck_execution_pace_runs_methodology_version"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_execution_pace_runs_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_pace_runs")),
    )
    op.create_index(
        op.f("ix_execution_pace_runs_portfolio_id"),
        "execution_pace_runs",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "execution_pace_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("target_revision_id", sa.Uuid(), nullable=True),
        sa.Column("holding_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("model_revision_id", sa.Uuid(), nullable=True),
        sa.Column("model_output_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("price_observation_id", sa.Uuid(), nullable=True),
        sa.Column("decision_status", sa.String(length=24), nullable=False),
        sa.Column("pace", sa.String(length=24), nullable=True),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "(decision_status = 'AVAILABLE' AND pace IS NOT NULL) OR "
            "(decision_status <> 'AVAILABLE' AND pace IS NULL)",
            name=op.f("ck_execution_pace_decisions_pace_status"),
        ),
        sa.CheckConstraint(
            "pace IS NULL OR pace IN ('ACCELERATE','BUILD','NORMAL_BUILD','SMALL_LADDER',"
            "'LADDER','HOLD','SLOW_LIMIT','WAIT_LIMIT','PATIENT_TRIM','TRIM_FASTER',"
            "'NORMAL_TRIM','PATIENT_EXIT','NORMAL_EXIT')",
            name=op.f("ck_execution_pace_decisions_pace"),
        ),
        sa.CheckConstraint(
            "decision_status IN ('AVAILABLE','REVIEW','UNAVAILABLE','NOT_APPLICABLE')",
            name=op.f("ck_execution_pace_decisions_decision_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_execution_pace_decisions_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["holding_snapshot_id"],
            ["holding_snapshots.id"],
            name=op.f("fk_execution_pace_decisions_holding_snapshot_id_holding_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_output_snapshot_id"],
            ["model_output_snapshots.id"],
            name=op.f(
                "fk_execution_pace_decisions_model_output_snapshot_id_model_output_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_revision_id"],
            ["financial_model_revisions.id"],
            name=op.f("fk_execution_pace_decisions_model_revision_id_financial_model_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["price_observation_id"],
            ["price_observations.id"],
            name=op.f("fk_execution_pace_decisions_price_observation_id_price_observations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["execution_pace_runs.id"],
            name=op.f("fk_execution_pace_decisions_run_id_execution_pace_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_revision_id"],
            ["target_allocation_revisions.id"],
            name=op.f("fk_execution_pace_decisions_target_revision_id_target_allocation_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_pace_decisions")),
        sa.UniqueConstraint("run_id", "company_id", name="uq_execution_pace_run_company"),
    )
    op.create_index(
        op.f("ix_execution_pace_decisions_company_id"),
        "execution_pace_decisions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_pace_decisions_run_id"),
        "execution_pace_decisions",
        ["run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_pace_decisions_run_id"), table_name="execution_pace_decisions")
    op.drop_index(
        op.f("ix_execution_pace_decisions_company_id"), table_name="execution_pace_decisions"
    )
    op.drop_table("execution_pace_decisions")
    op.drop_index(op.f("ix_execution_pace_runs_portfolio_id"), table_name="execution_pace_runs")
    op.drop_table("execution_pace_runs")
    # ### end Alembic commands ###
