"""canonical consensus estimate snapshots

Revision ID: 9747a3d3b279
Revises: c2f8ba7019de
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9747a3d3b279"
down_revision: str | Sequence[str] | None = "c2f8ba7019de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consensus_estimate_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=120), nullable=False),
        sa.Column("provider_schema_version", sa.String(length=120), nullable=True),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("source_reference", sa.String(length=1000), nullable=False),
        sa.Column("query_scope", sa.JSON(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_summary", sa.JSON(), nullable=False),
        sa.Column("reconciliation", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "domain = 'CONSENSUS_ESTIMATES'", name=op.f("ck_consensus_estimate_batches_domain")
        ),
        sa.CheckConstraint(
            "source_kind IN ('PROVIDER_RESPONSE','LEGACY_WORKBOOK')",
            name=op.f("ck_consensus_estimate_batches_source_kind"),
        ),
        sa.CheckConstraint(
            "length(source_digest) = 64", name=op.f("ck_consensus_estimate_batches_source_digest")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consensus_estimate_batches")),
        sa.UniqueConstraint(
            "source_digest",
            "normalizer_version",
            "observed_at",
            name="uq_consensus_estimate_batch_snapshot",
        ),
    )
    op.create_table(
        "consensus_estimate_provider_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=True),
        sa.Column("provider_id", sa.String(length=120), nullable=False),
        sa.Column("provider_symbol", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("evidence_source", sa.String(length=1000), nullable=False),
        sa.Column("currency_evidence_source", sa.String(length=1000), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')",
            name=op.f("ck_consensus_estimate_provider_mappings_actor"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_consensus_estimate_provider_mappings_currency"),
        ),
        sa.CheckConstraint(
            "role IN ('PRIMARY','FALLBACK')",
            name=op.f("ck_consensus_estimate_provider_mappings_role"),
        ),
        sa.CheckConstraint(
            "length(evidence_source) > 0",
            name=op.f("ck_consensus_estimate_provider_mappings_evidence_source"),
        ),
        sa.CheckConstraint(
            "priority >= 0", name=op.f("ck_consensus_estimate_provider_mappings_priority")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_consensus_estimate_provider_mappings_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_consensus_estimate_provider_mappings_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consensus_estimate_provider_mappings")),
        sa.UniqueConstraint(
            "company_id",
            "role",
            "provider_id",
            "effective_from",
            name="uq_consensus_estimate_mapping_company_source_effective",
        ),
        sa.UniqueConstraint(
            "provider_id", "provider_symbol", name="uq_consensus_provider_mapping_provider_symbol"
        ),
    )
    op.create_index(
        "ix_consensus_estimate_mapping_company_effective",
        "consensus_estimate_provider_mappings",
        ["company_id", "effective_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_estimate_provider_mappings_company_id"),
        "consensus_estimate_provider_mappings",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_estimate_provider_mappings_listing_id"),
        "consensus_estimate_provider_mappings",
        ["listing_id"],
        unique=False,
    )
    op.create_index(
        "uq_consensus_estimate_primary_company_effective",
        "consensus_estimate_provider_mappings",
        ["company_id", "effective_from"],
        unique=True,
        postgresql_where=sa.text("role = 'PRIMARY'"),
    )
    op.create_table(
        "consensus_estimate_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=True),
        sa.Column("provider_mapping_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=120), nullable=False),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("forecast_period", sa.String(length=80), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("value", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("low_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("high_value", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("analyst_count", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_record_id", sa.String(length=500), nullable=False),
        sa.Column("source_ref", sa.String(length=1000), nullable=False),
        sa.Column("revision_context", sa.String(length=24), nullable=False),
        sa.Column("data_quality", sa.String(length=16), nullable=False),
        sa.Column("quality_reason", sa.String(length=1000), nullable=True),
        sa.Column("supersedes_observation_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "currency IS NULL OR currency ~ '^[A-Z]{3}$'",
            name=op.f("ck_consensus_estimate_observations_currency"),
        ),
        sa.CheckConstraint(
            "data_quality IN ('PASS','DATA_CHECK','INVALID')",
            name=op.f("ck_consensus_estimate_observations_data_quality"),
        ),
        sa.CheckConstraint(
            "metric IN ('REVENUE','EPS')", name=op.f("ck_consensus_estimate_observations_metric")
        ),
        sa.CheckConstraint(
            "period_type IN ('ANNUAL','QUARTERLY')",
            name=op.f("ck_consensus_estimate_observations_period_type"),
        ),
        sa.CheckConstraint(
            "revision_context IN ('SNAPSHOT','REVISED','LEGACY_BASELINE')",
            name=op.f("ck_consensus_estimate_observations_revision_context"),
        ),
        sa.CheckConstraint(
            "(low_value IS NULL OR low_value <= value) AND "
            "(high_value IS NULL OR high_value >= value) AND "
            "(low_value IS NULL OR high_value IS NULL OR low_value <= high_value)",
            name=op.f("ck_consensus_estimate_observations_range_order"),
        ),
        sa.CheckConstraint(
            "analyst_count IS NULL OR analyst_count >= 0",
            name=op.f("ck_consensus_estimate_observations_analyst_count"),
        ),
        sa.CheckConstraint(
            "length(forecast_period) > 0",
            name=op.f("ck_consensus_estimate_observations_forecast_period"),
        ),
        sa.CheckConstraint(
            "value IS NOT NULL", name=op.f("ck_consensus_estimate_observations_value_required")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["consensus_estimate_batches.id"],
            name=op.f("fk_consensus_estimate_observations_batch_id_consensus_estimate_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_consensus_estimate_observations_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_consensus_estimate_observations_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_mapping_id"],
            ["consensus_estimate_provider_mappings.id"],
            name=op.f(
                "fk_consensus_estimate_observations_provider_mapping_id_consensus_estimate_provider_mappings"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_observation_id"],
            ["consensus_estimate_observations.id"],
            name="fk_consensus_estimate_supersedes",
            ondelete="RESTRICT",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consensus_estimate_observations")),
        sa.UniqueConstraint(
            "batch_id", "source_record_id", name="uq_consensus_estimate_batch_source_record"
        ),
    )
    op.create_index(
        op.f("ix_consensus_estimate_observations_batch_id"),
        "consensus_estimate_observations",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_estimate_observations_company_id"),
        "consensus_estimate_observations",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_estimate_observations_listing_id"),
        "consensus_estimate_observations",
        ["listing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consensus_estimate_observations_provider_mapping_id"),
        "consensus_estimate_observations",
        ["provider_mapping_id"],
        unique=False,
    )
    op.create_index(
        "ix_consensus_estimates_company_metric_period",
        "consensus_estimate_observations",
        ["company_id", "metric", "period_end"],
        unique=False,
    )
    op.create_index(
        "ix_consensus_estimates_company_observed",
        "consensus_estimate_observations",
        ["company_id", "snapshot_date", "observed_at"],
        unique=False,
    )
    op.add_column(
        "external_raw_payloads", sa.Column("consensus_estimate_batch_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_external_raw_payloads_consensus_estimate_batch_id"),
        "external_raw_payloads",
        ["consensus_estimate_batch_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_external_payload_consensus_batch_record",
        "external_raw_payloads",
        ["consensus_estimate_batch_id", "source_record_id"],
    )
    op.create_foreign_key(
        "fk_external_raw_payloads_consensus_batch",
        "external_raw_payloads",
        "consensus_estimate_batches",
        ["consensus_estimate_batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.execute(
        """DO $$ DECLARE item record; BEGIN
        FOR item IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'external_raw_payloads'::regclass
              AND contype = 'c'
              AND lower(pg_get_constraintdef(oid)) LIKE '%num_nonnulls%'
              AND (
                  lower(pg_get_constraintdef(oid)) LIKE '%reported_fundamental_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%consensus_estimate_batch_id%'
              )
        LOOP
            EXECUTE format('ALTER TABLE external_raw_payloads DROP CONSTRAINT %I', item.conname);
        END LOOP;
        END $$"""
    )
    op.create_check_constraint(
        op.f("ck_external_raw_payloads_exactly_one_batch"),
        "external_raw_payloads",
        "num_nonnulls(batch_id, reported_fundamental_batch_id, consensus_estimate_batch_id) = 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """DO $$ DECLARE item record; BEGIN
        FOR item IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'external_raw_payloads'::regclass
              AND contype = 'c'
              AND lower(pg_get_constraintdef(oid)) LIKE '%num_nonnulls%'
              AND (
                  lower(pg_get_constraintdef(oid)) LIKE '%reported_fundamental_batch_id%'
                  OR lower(pg_get_constraintdef(oid)) LIKE '%consensus_estimate_batch_id%'
              )
        LOOP
            EXECUTE format('ALTER TABLE external_raw_payloads DROP CONSTRAINT %I', item.conname);
        END LOOP;
        END $$"""
    )
    op.create_check_constraint(
        op.f("ck_external_raw_payloads_exactly_one_batch"),
        "external_raw_payloads",
        "num_nonnulls(batch_id, reported_fundamental_batch_id) = 1",
    )
    op.drop_constraint(
        "fk_external_raw_payloads_consensus_batch", "external_raw_payloads", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_external_payload_consensus_batch_record", "external_raw_payloads", type_="unique"
    )
    op.drop_index(
        op.f("ix_external_raw_payloads_consensus_estimate_batch_id"),
        table_name="external_raw_payloads",
    )
    op.drop_column("external_raw_payloads", "consensus_estimate_batch_id")
    op.drop_index(
        "ix_consensus_estimates_company_observed", table_name="consensus_estimate_observations"
    )
    op.drop_index(
        "ix_consensus_estimates_company_metric_period", table_name="consensus_estimate_observations"
    )
    op.drop_index(
        op.f("ix_consensus_estimate_observations_provider_mapping_id"),
        table_name="consensus_estimate_observations",
    )
    op.drop_index(
        op.f("ix_consensus_estimate_observations_listing_id"),
        table_name="consensus_estimate_observations",
    )
    op.drop_index(
        op.f("ix_consensus_estimate_observations_company_id"),
        table_name="consensus_estimate_observations",
    )
    op.drop_index(
        op.f("ix_consensus_estimate_observations_batch_id"),
        table_name="consensus_estimate_observations",
    )
    op.drop_table("consensus_estimate_observations")
    op.drop_index(
        "uq_consensus_estimate_primary_company_effective",
        table_name="consensus_estimate_provider_mappings",
        postgresql_where=sa.text("role = 'PRIMARY'"),
    )
    op.drop_index(
        op.f("ix_consensus_estimate_provider_mappings_listing_id"),
        table_name="consensus_estimate_provider_mappings",
    )
    op.drop_index(
        op.f("ix_consensus_estimate_provider_mappings_company_id"),
        table_name="consensus_estimate_provider_mappings",
    )
    op.drop_index(
        "ix_consensus_estimate_mapping_company_effective",
        table_name="consensus_estimate_provider_mappings",
    )
    op.drop_table("consensus_estimate_provider_mappings")
    op.drop_table("consensus_estimate_batches")
    # ### end Alembic commands ###
