"""milestone 1a universe and portfolio

Revision ID: a57efdd8015f
Revises: 0001_platform_baseline
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a57efdd8015f"
down_revision: str | Sequence[str] | None = "0001_platform_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("reporting_currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_table(
        "portfolios",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
    )
    op.create_table(
        "holding_snapshots",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("completeness", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_holding_snapshots_actor")
        ),
        sa.CheckConstraint(
            "completeness IN ('COMPLETE','PARTIAL','UNAVAILABLE')",
            name=op.f("ck_holding_snapshots_completeness"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_holding_snapshots_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holding_snapshots")),
        sa.UniqueConstraint(
            "portfolio_id", "effective_at", name=op.f("uq_holding_snapshots_portfolio_id")
        ),
    )
    op.create_index(
        op.f("ix_holding_snapshots_portfolio_id"),
        "holding_snapshots",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "lifecycle_events",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("previous_state", sa.String(length=16), nullable=True),
        sa.Column("new_state", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_lifecycle_events_actor")
        ),
        sa.CheckConstraint(
            "new_state IN ('PORTFOLIO','WATCHLIST','CANDIDATE','DROP')",
            name=op.f("ck_lifecycle_events_new_state"),
        ),
        sa.CheckConstraint(
            "previous_state IS NULL OR "
            "previous_state IN ('PORTFOLIO','WATCHLIST','CANDIDATE','DROP')",
            name=op.f("ck_lifecycle_events_previous_state"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_lifecycle_events_sequence")),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_lifecycle_events_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lifecycle_events")),
        sa.UniqueConstraint("company_id", "id", name="uq_lifecycle_events_company_event"),
        sa.UniqueConstraint("company_id", "sequence", name=op.f("uq_lifecycle_events_company_id")),
    )
    op.create_index(
        op.f("ix_lifecycle_events_company_id"), "lifecycle_events", ["company_id"], unique=False
    )
    op.create_table(
        "securities",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("security_type", sa.String(length=32), nullable=False),
        sa.Column("share_class", sa.String(length=80), nullable=True),
        sa.Column("underlying_security_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "security_type IN ('COMMON_STOCK', 'ADR', 'PREFERRED')", name=op.f("ck_securities_type")
        ),
        sa.CheckConstraint(
            "underlying_security_id IS NULL OR underlying_security_id <> id",
            name=op.f("ck_securities_underlying"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_securities_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["underlying_security_id"],
            ["securities.id"],
            name=op.f("fk_securities_underlying_security_id_securities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_securities")),
    )
    op.create_index(op.f("ix_securities_company_id"), "securities", ["company_id"], unique=False)
    op.create_table(
        "target_allocation_revisions",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "(status = 'DRAFT' AND accepted_at IS NULL) OR "
            "(status = 'ACCEPTED' AND accepted_at IS NOT NULL)",
            name=op.f("ck_target_allocation_revisions_acceptance"),
        ),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')",
            name=op.f("ck_target_allocation_revisions_actor"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACCEPTED')", name=op.f("ck_target_allocation_revisions_status")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_target_allocation_revisions_portfolio_id_portfolios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_allocation_revisions")),
    )
    op.create_index(
        op.f("ix_target_allocation_revisions_portfolio_id"),
        "target_allocation_revisions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "company_lifecycle_current",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id", "event_id"],
            ["lifecycle_events.company_id", "lifecycle_events.id"],
            name=op.f("fk_company_lifecycle_current_company_id_lifecycle_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_lifecycle_current_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("company_id", name=op.f("pk_company_lifecycle_current")),
        sa.UniqueConstraint("event_id", name=op.f("uq_company_lifecycle_current_event_id")),
    )
    op.create_table(
        "holding_cash_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("balance", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.CheckConstraint(
            "balance IS NULL OR balance >= 0", name=op.f("ck_holding_cash_positions_balance")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["holding_snapshots.id"],
            name=op.f("fk_holding_cash_positions_snapshot_id_holding_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holding_cash_positions")),
        sa.UniqueConstraint(
            "snapshot_id", "currency", name=op.f("uq_holding_cash_positions_snapshot_id")
        ),
    )
    op.create_index(
        op.f("ix_holding_cash_positions_snapshot_id"),
        "holding_cash_positions",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "listings",
        sa.Column("security_id", sa.Uuid(), nullable=False),
        sa.Column("venue", sa.String(length=80), nullable=False),
        sa.Column("ticker", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_listings_security_id_securities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("venue", "ticker", name=op.f("uq_listings_venue")),
    )
    op.create_index(op.f("ix_listings_security_id"), "listings", ["security_id"], unique=False)
    op.create_table(
        "target_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.CheckConstraint(
            "weight >= 0 AND weight <= 1", name=op.f("ck_target_allocations_weight")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_target_allocations_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["target_allocation_revisions.id"],
            name=op.f("fk_target_allocations_revision_id_target_allocation_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_allocations")),
        sa.UniqueConstraint(
            "revision_id", "company_id", name=op.f("uq_target_allocations_revision_id")
        ),
    )
    op.create_index(
        op.f("ix_target_allocations_revision_id"),
        "target_allocations",
        ["revision_id"],
        unique=False,
    )
    op.create_table(
        "holding_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity >= 0", name=op.f("ck_holding_positions_quantity")
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_holding_positions_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["holding_snapshots.id"],
            name=op.f("fk_holding_positions_snapshot_id_holding_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holding_positions")),
        sa.UniqueConstraint(
            "snapshot_id", "listing_id", name=op.f("uq_holding_positions_snapshot_id")
        ),
    )
    op.create_index(
        op.f("ix_holding_positions_snapshot_id"), "holding_positions", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holding_positions_snapshot_id"), table_name="holding_positions")
    op.drop_table("holding_positions")
    op.drop_index(op.f("ix_target_allocations_revision_id"), table_name="target_allocations")
    op.drop_table("target_allocations")
    op.drop_index(op.f("ix_listings_security_id"), table_name="listings")
    op.drop_table("listings")
    op.drop_index(
        op.f("ix_holding_cash_positions_snapshot_id"), table_name="holding_cash_positions"
    )
    op.drop_table("holding_cash_positions")
    op.drop_table("company_lifecycle_current")
    op.drop_index(
        op.f("ix_target_allocation_revisions_portfolio_id"),
        table_name="target_allocation_revisions",
    )
    op.drop_table("target_allocation_revisions")
    op.drop_index(op.f("ix_securities_company_id"), table_name="securities")
    op.drop_table("securities")
    op.drop_index(op.f("ix_lifecycle_events_company_id"), table_name="lifecycle_events")
    op.drop_table("lifecycle_events")
    op.drop_index(op.f("ix_holding_snapshots_portfolio_id"), table_name="holding_snapshots")
    op.drop_table("holding_snapshots")
    op.drop_table("portfolios")
    op.drop_table("companies")
    # ### end Alembic commands ###
