"""Preserve exact four-decimal score observations

Revision ID: a5bfc471caef
Revises: 45571a6d359b
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a5bfc471caef"
down_revision: str | Sequence[str] | None = "45571a6d359b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_assessments",
        "score",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        type_=sa.Numeric(precision=6, scale=4),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "score_assessments",
        "score",
        existing_type=sa.Numeric(precision=6, scale=4),
        type_=sa.NUMERIC(precision=4, scale=3),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
