"""Track legacy workbook import batches and standalone ETFs

Revision ID: ac6e0a489b51
Revises: f93584e17442
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ac6e0a489b51"
down_revision: str | Sequence[str] | None = "f93584e17442"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("portfolio_workbook_sha256", sa.String(length=64), nullable=False),
        sa.Column("market_data_sha256", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.CheckConstraint("status IN ('APPLIED')", name=op.f("ck_legacy_import_batches_status")),
        sa.CheckConstraint(
            "length(source_digest) = 64", name=op.f("ck_legacy_import_batches_source_digest")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_import_batches")),
        sa.UniqueConstraint("source_digest", name=op.f("uq_legacy_import_batches_source_digest")),
    )
    op.alter_column("securities", "company_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("ck_securities_type"), "securities", type_="check")
    op.create_check_constraint(
        op.f("ck_securities_type"),
        "securities",
        "security_type IN ('COMMON_STOCK', 'ADR', 'PREFERRED', 'ETF')",
    )
    op.create_check_constraint(
        op.f("ck_securities_issuer"),
        "securities",
        "(security_type = 'ETF' AND company_id IS NULL) OR "
        "(security_type <> 'ETF' AND company_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_securities_issuer"), "securities", type_="check")
    op.drop_constraint(op.f("ck_securities_type"), "securities", type_="check")
    op.create_check_constraint(
        op.f("ck_securities_type"),
        "securities",
        "security_type IN ('COMMON_STOCK', 'ADR', 'PREFERRED')",
    )
    op.alter_column("securities", "company_id", existing_type=sa.UUID(), nullable=False)
    op.drop_table("legacy_import_batches")
    # ### end Alembic commands ###
