"""preserve provider price units and evidence for verified listing imports

Revision ID: c4a8f6d21e90
Revises: b1f65d019d22
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4a8f6d21e90"
down_revision: str | Sequence[str] | None = "b1f65d019d22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    batch_checks = {item["name"] for item in inspector.get_check_constraints("market_data_batches")}
    # The initial local upgrade partially committed this named check before failing on a
    # duplicate. Normalize it to the name generated by the model metadata convention.
    legacy_check = "ck_market_data_batches_ck_market_data_batches_source_kind"
    expected_check = "ck_market_data_batches_source_kind"
    if legacy_check in batch_checks:
        op.drop_constraint(op.f(legacy_check), "market_data_batches", type_="check")
    if expected_check not in batch_checks:
        op.create_check_constraint(
            op.f(expected_check),
            "market_data_batches",
            "source_kind IN ('WORKBOOK_SNAPSHOT','PROVIDER_RESPONSE')",
        )

    price_columns = {item["name"] for item in inspector.get_columns("price_observations")}
    if "provider_currency" not in price_columns:
        op.add_column(
            "price_observations",
            sa.Column("provider_currency", sa.String(8), nullable=True),
        )
    if "source_price_multiplier" not in price_columns:
        op.add_column(
            "price_observations",
            sa.Column(
                "source_price_multiplier",
                sa.Numeric(20, 8),
                nullable=False,
                server_default="1",
            ),
        )
    # Backfilling legacy observation provenance can touch the full imported price
    # history, so avoid inheriting a short interactive statement timeout.
    op.execute("SET LOCAL statement_timeout = 0")
    op.execute(
        "UPDATE price_observations SET provider_currency = currency WHERE provider_currency IS NULL"
    )

    action_columns = {item["name"] for item in inspector.get_columns("corporate_actions")}
    if "provider_cash_amount" not in action_columns:
        op.add_column(
            "corporate_actions",
            sa.Column("provider_cash_amount", sa.Numeric(28, 10), nullable=True),
        )
    if "provider_cash_currency" not in action_columns:
        op.add_column(
            "corporate_actions", sa.Column("provider_cash_currency", sa.String(8), nullable=True)
        )
    action_checks = {item["name"] for item in inspector.get_check_constraints("corporate_actions")}
    action_check = "ck_corporate_actions_cash_dividend"
    action_legacy_check = "ck_corporate_actions_ck_corporate_actions_cash_dividend"
    if action_legacy_check in action_checks:
        op.drop_constraint(op.f(action_legacy_check), "corporate_actions", type_="check")
    if action_check not in action_checks:
        op.create_check_constraint(
            op.f(action_check),
            "corporate_actions",
            "(cash_amount IS NULL AND cash_currency IS NULL) OR "
            "(cash_amount > 0 AND cash_currency IS NOT NULL)",
        )
    listing_columns = {item["name"] for item in inspector.get_columns("listings")}
    if "identity_source_ref" not in listing_columns:
        op.add_column("listings", sa.Column("identity_source_ref", sa.String(500), nullable=True))


def downgrade() -> None:
    op.drop_column("listings", "identity_source_ref")
    op.drop_constraint(
        op.f("ck_corporate_actions_cash_dividend"), "corporate_actions", type_="check"
    )
    op.drop_column("corporate_actions", "provider_cash_currency")
    op.drop_column("corporate_actions", "provider_cash_amount")
    op.drop_column("price_observations", "source_price_multiplier")
    op.drop_column("price_observations", "provider_currency")
    op.drop_constraint(
        op.f("ck_market_data_batches_source_kind"), "market_data_batches", type_="check"
    )
