"""scope source document identity by company

Revision ID: efbcaa0ca40c
Revises: 508a1bb35c90
"""

from collections.abc import Sequence

from alembic import op

revision: str = "efbcaa0ca40c"
down_revision: str | Sequence[str] | None = "508a1bb35c90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_source_document_provider_external_id"), "source_documents", type_="unique"
    )
    op.create_unique_constraint(
        "uq_source_document_company_provider_external_id",
        "source_documents",
        ["company_id", "provider_id", "external_identifier"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_source_document_company_provider_external_id", "source_documents", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_source_document_provider_external_id"),
        "source_documents",
        ["provider_id", "external_identifier"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
