"""milestone 1c auditable ranking runs

Revision ID: f93584e17442
Revises: 4cef0ea57fba
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import UUID

import sqlalchemy as sa
from alembic import op

revision: str = "f93584e17442"
down_revision: str | Sequence[str] | None = "4cef0ea57fba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ranking_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ranking_type", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=False),
        sa.Column("population_rule", sa.Text(), nullable=False),
        sa.Column("required_inputs", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=False),
        sa.Column("implementation_status", sa.String(length=24), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "implementation_status IN ('NOT_MIGRATED','PARTIAL','READY')",
            name=op.f("ck_ranking_definitions_implementation_status"),
        ),
        sa.CheckConstraint(
            "ranking_type IN ('PORTFOLIO','WATCHLIST','RESEARCH')",
            name=op.f("ck_ranking_definitions_ranking_type"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED')", name=op.f("ck_ranking_definitions_status")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_ranking_definitions_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_definitions")),
        sa.UniqueConstraint(
            "ranking_type", "version", name=op.f("uq_ranking_definitions_ranking_type")
        ),
    )
    op.create_index(
        "uq_ranking_definitions_one_active_per_type",
        "ranking_definitions",
        ["ranking_type"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "ranking_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("definition_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "actor IN ('LOCAL_USER','SYSTEM','IMPORT')", name=op.f("ck_ranking_runs_actor")
        ),
        sa.CheckConstraint(
            "status IN ('COMPLETE','PARTIAL','UNAVAILABLE')", name=op.f("ck_ranking_runs_status")
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["ranking_definitions.id"],
            name=op.f("fk_ranking_runs_definition_id_ranking_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_runs")),
    )
    op.create_index(
        op.f("ix_ranking_runs_definition_id"), "ranking_runs", ["definition_id"], unique=False
    )
    op.create_table(
        "ranking_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.CheckConstraint(
            "(status = 'RANKED' AND position IS NOT NULL AND position > 0) OR "
            "(status <> 'RANKED' AND position IS NULL)",
            name=op.f("ck_ranking_entries_position_status"),
        ),
        sa.CheckConstraint(
            "status IN ('RANKED','INPUTS_UNAVAILABLE','NOT_ELIGIBLE','EXCLUDED','NOT_MIGRATED')",
            name=op.f("ck_ranking_entries_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_ranking_entries_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ranking_runs.id"],
            name=op.f("fk_ranking_entries_run_id_ranking_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_entries")),
        sa.UniqueConstraint("run_id", "company_id", name=op.f("uq_ranking_entries_run_company")),
        sa.UniqueConstraint("run_id", "position", name=op.f("uq_ranking_entries_run_position")),
    )
    op.create_index(
        op.f("ix_ranking_entries_company_id"), "ranking_entries", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_ranking_entries_run_id"), "ranking_entries", ["run_id"], unique=False)

    definitions = sa.table(
        "ranking_definitions",
        sa.column("id", sa.Uuid()),
        sa.column("ranking_type", sa.String()),
        sa.column("version", sa.Integer()),
        sa.column("title", sa.String()),
        sa.column("methodology", sa.Text()),
        sa.column("population_rule", sa.Text()),
        sa.column("required_inputs", sa.Text()),
        sa.column("source_reference", sa.String()),
        sa.column("implementation_status", sa.String()),
        sa.column("effective_from", sa.DateTime(timezone=True)),
        sa.column("status", sa.String()),
        sa.column("recorded_at", sa.DateTime(timezone=True)),
    )
    effective_from = datetime(2026, 10, 4, tzinfo=UTC)
    op.bulk_insert(
        definitions,
        [
            {
                "id": UUID("f9300000-0000-4000-8000-000000000001"),
                "ranking_type": "PORTFOLIO",
                "version": 1,
                "title": "Portfolio Rank",
                "methodology": (
                    "The workbook assigns position = 1 + count of higher Portfolio Score "
                    "+ count of equal Portfolio Score with lexically earlier ticker. A missing "
                    "Portfolio Score leaves rank blank. The source metric is not migrated, so "
                    "this version records availability and emits no numeric positions."
                ),
                "population_rule": (
                    "The Portfolio decision view includes companies with positive current "
                    "weight or positive target weight. Current weight requires comparable "
                    "prices and FX; eligibility remains unavailable when these observations "
                    "are incomplete."
                ),
                "required_inputs": (
                    "Universe Registry Portfolio Score (column O), its underlying authored "
                    "inputs, current holdings valued in portfolio currency, and accepted "
                    "target allocations."
                ),
                "source_reference": (
                    "Portfolio_Watchlist.xlsx: Universe Registry!L4:O; Portfolio!A4:G"
                ),
                "implementation_status": "NOT_MIGRATED",
                "effective_from": effective_from,
                "status": "ACTIVE",
                "recorded_at": effective_from,
            },
            {
                "id": UUID("f9300000-0000-4000-8000-000000000002"),
                "ranking_type": "WATCHLIST",
                "version": 1,
                "title": "Watchlist Rank (IRR-first)",
                "methodology": (
                    "The canonical IRR-first rank is position = 1 + count of higher Expected "
                    "IRR + count of equal Expected IRR with lexically earlier ticker. A missing "
                    "Expected IRR leaves rank blank. Expected IRR is not migrated, so this "
                    "version records availability and emits no numeric positions. The separate "
                    "Portfolio Candidate Rank by Fit Tier then Expected IRR is not conflated "
                    "with this ranking type."
                ),
                "population_rule": (
                    "Only companies with explicit WATCHLIST lifecycle are in the canonical "
                    "Watchlist Rank population."
                ),
                "required_inputs": (
                    "Canonical Expected Cash-Flow IRR in the comparable model currency and "
                    "explicit WATCHLIST lifecycle."
                ),
                "source_reference": (
                    "Portfolio_Watchlist.xlsx: Universe Registry!H4:M; Watchlist!A4:C"
                ),
                "implementation_status": "NOT_MIGRATED",
                "effective_from": effective_from,
                "status": "ACTIVE",
                "recorded_at": effective_from,
            },
            {
                "id": UUID("f9300000-0000-4000-8000-000000000003"),
                "ranking_type": "RESEARCH",
                "version": 1,
                "title": "Research Rank",
                "methodology": (
                    "The workbook assigns position = 1 + count of higher Research Sort Key "
                    "+ count of equal sort key with lexically earlier ticker. A missing sort "
                    "key leaves rank blank. The key and its source are not migrated, so this "
                    "version records availability and emits no numeric positions."
                ),
                "population_rule": (
                    "Only company research records with a populated canonical Research Sort "
                    "Key are ranked. The research-record domain is not yet migrated."
                ),
                "required_inputs": (
                    "Canonical Research Sort Key and the company research record that owns "
                    "that key."
                ),
                "source_reference": (
                    "Portfolio_Watchlist.xlsx: Universe Registry!J4:Q; Research Universe!A4"
                ),
                "implementation_status": "NOT_MIGRATED",
                "effective_from": effective_from,
                "status": "ACTIVE",
                "recorded_at": effective_from,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ranking_entries_run_id"), table_name="ranking_entries")
    op.drop_index(op.f("ix_ranking_entries_company_id"), table_name="ranking_entries")
    op.drop_table("ranking_entries")
    op.drop_index(op.f("ix_ranking_runs_definition_id"), table_name="ranking_runs")
    op.drop_table("ranking_runs")
    op.drop_index(
        "uq_ranking_definitions_one_active_per_type",
        table_name="ranking_definitions",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("ranking_definitions")
